### ISSUE TITLE
Any chance you can intergrate this with lightfx-extender

### ISSUE THREAD

**Issue by fma965** [Palmr/LibCorsairRGB#2]
Any chance you can integrate this with https://github.com/Archomeda/lightfx-extender

It makes the Alienwares AlienFX SDK and LightFX.dll work with Logitech and Lightpak devices

**Comment by Palmr** [comment]
I've not heard of LightFX before, and unfortunately I don't have any games that work with it to test against.

I could collaborate with you make the integration if you want (email me if you want), but for now I'll mark this issue as closed as I don't have any plans to look at it currently.
